package xmu.ackerman.zparse_http;

public enum ParseRequestState {
    PARSE_START,

    HEADER_METHOD,
    HEADER_HTTP,
    HEADER_HTTP_H,
    HEADER_HTTP_HT,
    HEADER_HTTP_HTT,
    HEADER_HTTP_HTTP,
    HEADER_MAJOR_DIGIT,
    HEADER_MINOR_DIGIT,
    HEADER_FIRST_MAJOR_DIGIT,
    HEADER_FIRST_MINOR_DIGIT,
    HEADER_SPACES_AFTER_DIGIT,
    HEADER_SPACES_BEFORE_URI,
    HEADER_AFTER_SLASH_IN_URI,

    BODY_CR,
    BODY_CRLF,
    BODY_CRLFCR,
    BODY_KEY,
    BODY_VALUE,
    BODY_SPACES_BEFORE_COLON,
    BODY_SPACES_AFTER_COLON,

    PARSE_ALMOST_DONE
}
